### PR TITLE
Fix deletion bugs in various places

### LINKED ISSUE #72: Deletion of postgrestandalone in loop
### Description

The deletion of postgresqlstandalone CRD is not possible when the connection secret was not created in the first place. This particular case can occur when a deletion operation is issued right after creation or in case the connection secret was not created for any other reason.

### Additional Context

Connection secret is created during second reconciliation phase which means there is a time frame where the deletion is not possible with current version. When deletion happens on that particular moment, the field [Name](https://github.com/vshn/appcat-service-postgresql/blob/master/operator/standalone/delete.go#L82) is empty thus the client returns `resource name may not be empty` error. See logs for further details.

### Logs

```shell
2022-06-10T12:37:06.923Z | ERROR | provider-postgresql.operator | controller/controller.go:326 | Reconciler error | {"controller": "postgresqlstandalone.postgresql.appcat.vshn.io", "controllerGroup": "postgresql.appcat.vshn.io", "controllerKind": "PostgresqlStandalone", "postgresqlStandalone": {"name":"my-instance","namespace":"default"}, "namespace": "default", "name": "my-instance", "reconcileID": "bc25a635-d4bb-4b3d-8a5a-d6296737d066", "error": "step \"delete connection secret\" failed: resource name may not be empty"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/Users/gabrielsaratura/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.0/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/gabrielsaratura/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.0/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/Users/gabrielsaratura/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.0/pkg/internal/controller/controller.go:234
```

### Expected Behavior

Deletion is done successfully even when the `writeConnectionSecretToRef` is not populated.

### Steps To Reproduce

```bash
make local-install install-samples &&  \
kind get kubeconfig --name appcat-service-postgresql-v1.24.0 > ~/.kube/config && \
sleep 3 && \
kubectl delete postgresqlstandalone my-instance -n default
```

### Versions

master, latest

### PR DESCRIPTION
**Pull request by ccremer**
## Summary

* Closes #72
* Fixes panics where the name of the connection secret is empty in case it wasn't set by the webhook that sets defaults.

### For Code changes

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] PR contains the label `area:operator`
- [x] Link this PR to related issues
- [x] I have not made _any_ changes in the `charts/` directory.

### CODE REVIEW

File: operator/standalone/delete_it_test.go [hunk 1]
```diff
@@ -166,16 +145,6 @@ func (ts *DeleteStandalonePipelineSuite) Test_DeleteConnectionSecret() {
...
-		"GivenExistingSecret_WhenDeletingGeneratesAnError_ThenReturnError": {
-			prepare: func(name, namespace string) {
-				ts.EnsureNS(namespace)
-				ts.EnsureResources(&corev1.Secret{ObjectMeta: metav1.ObjectMeta{Name: "secret", Namespace: namespace}})
-			},
-			givenNamespace: "test-namespace",
-			// we purposefully set namespace to empty so that we generate an error so that we avoid mocking.
-			givenSecret:   "",
-			expectedError: "resource name may not be empty",
-		},
```
Comment (ccremer) [inline operator/standalone/delete_it_test.go:178]: @A note on why I removed this and similar test cases:
Previously, it was tested whether the function under test returns an error if the Delete() func from the client returned an error. We did trigger this error by not setting a name, which returns "resource name may not be empty". But not setting a name is basically an exploit of the exact bug that I'm about to fix in this PR. Thus, I don't see any other easy way to trigger an error without getting involved in mocking or using the fake client.

However, I don't see covering the Delete() func from the client worth to test at this stage right now. The more important logic is already covered and can be verified.

Comment (ZuGao) [reply operator/standalone/delete_it_test.go:178]: For me it's fine to remove it. If we want to do proper testing we need mocks and end-to-end tests. This specific test case is just a coincidence to what happened in the real world scenario which by the way should have been caught with an end-to-end test.

**Review by ZuGao — APPROVED** [review]
LGTM

**Comment by ZuGao** [comment]
Please add in the Summary that you are also fixing a the connection secret name bug which happens when webhooks are disabled.
